import Header from "@/components/header";
import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import { Lato } from 'next/font/google';
import { Be_Vietnam_Pro } from "next/font/google";
import type { Metadata } from "next";
import "../styles/global.scss";
import Footer from "@/components/footer";




const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-lato',
  display: 'swap',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body
        className={`${inter.variable}  ${lato.variable} antialiased`}
      >
         <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
